In [1]:
# ライブラリ
import numpy as np
from scipy import stats
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
# データ準備
df = sns.load_dataset('tips')
df['tip_rate'] = df['tip'] / df['total_bill']
df

total_bill   tip     sex smoker   day    time  size  tip_rate
0         16.99  1.01  Female     No   Sun  Dinner     2  0.059447
1         10.34  1.66    Male     No   Sun  Dinner     3  0.160542
2         21.01  3.50    Male     No   Sun  Dinner     3  0.166587
3         23.68  3.31    Male     No   Sun  Dinner     2  0.139780
4         24.59  3.61  Female     No   Sun  Dinner     4  0.146808
..          ...   ...     ...    ...   ...     ...   ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3  0.203927
240       27.18  2.00  Female    Yes   Sat  Dinner     2  0.073584
241       22.67  2.00    Male    Yes   Sat  Dinner     2  0.088222
242       17.82  1.75    Male     No   Sat  Dinner     2  0.098204
243       18.78  3.00  Female     No  Thur  Dinner     2  0.159744

[244 rows x 8 columns]

### 共分散

In [6]:
np.cov([1,2,3], [-4,5,6], bias=True)  # bias = Trueで普通の共分散、つけないとn-1でわる普遍共分散になる

array([[ 0.66666667,  3.33333333],
       [ 3.33333333, 20.22222222]])

In [7]:
np.cov(df['total_bill'], df['tip'], bias=True)

array([[78.92813149,  8.28938892],
       [ 8.28938892,  1.90660851]])

In [11]:
x = np.stack([df['total_bill'], df['tip'], df['size']], axis=0)
np.cov(x, bias=True)

array([[78.92813149,  8.28938892,  5.04522121],
       [ 8.28938892,  1.90660851,  0.64126747],
       [ 5.04522121,  0.64126747,  0.9008835 ]])

In [17]:
df_x = pd.DataFrame(x)

In [27]:
df_sample = pd.DataFrame({
    'tip':df['tip'],
    'tip_rate':df['tip_rate'],
})
df_sample

tip  tip_rate
0    1.01  0.059447
1    1.66  0.160542
2    3.50  0.166587
3    3.31  0.139780
4    3.61  0.146808
..    ...       ...
239  5.92  0.203927
240  2.00  0.073584
241  2.00  0.088222
242  1.75  0.098204
243  3.00  0.159744

[244 rows x 2 columns]

In [30]:
df_sample.cov()  # 共分散行列、ちなみにdf.cov()は不偏共分散つまりn-1で割っている

tip  tip_rate
tip       1.914455  0.028931
tip_rate  0.028931  0.003730